stages:
  - dep
  - build

dep:
  stage: dep
  image: golang:1.9
  script:
    - go build /home/osman/projects/turkai/app/main.go 

build:
  stage: build
  image: docker:17
  dependencies:
    - dep
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t registry.gitlab.com/osmanfaruko/turkai-ex/goapp:latest ./app
    - docker push registry.gitlab.com/osmanfaruko/turkai-ex/goapp:latest

