stages:
  - dep
  - build

dep:
  stage: dep
  image: golang:1.9
  script:
    - GOOS=linux GOARCH=386 go build -o ./app/main ./app/main.go

build:
  stage: build
  image: docker:stable
  services:
    - docker:dind
  dependencies:
    - dep
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY/osmanfaruko/turkai-ex/goapp:latest ./app
    - docker tag $CI_REGISTRY/osmanfaruko/turkai-ex/goapp:latest $CI_REGISTRY/osmanfaruko/turkai-ex/goapp:$CI_COMMIT_SHORT_SHA
    - docker push $CI_REGISTRY/osmanfaruko/turkai-ex/goapp:latest
    - docker push $CI_REGISTRY/osmanfaruko/turkai-ex/goapp:$CI_COMMIT_SHORT_SHA
    - docker build -t $CI_REGISTRY/osmanfaruko/turkai-ex/nginx:latest ./nginx
    - docker tag $CI_REGISTRY/osmanfaruko/turkai-ex/nginx:latest $CI_REGISTRY/osmanfaruko/turkai-ex/nginx:$CI_COMMIT_SHORT_SHA
    - docker push $CI_REGISTRY/osmanfaruko/turkai-ex/nginx:latest
    - docker push $CI_REGISTRY/osmanfaruko/turkai-ex/nginx:$CI_COMMIT_SHORT_SHA