version: '3'

services:
  goapp:
    build: ./app
    networks:
      env-network:

  nginx:
    image: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    command: [nginx-debug, '-g', 'daemon off;']
    depends_on:
      - goapp
    ports:
      - '80:80'
      - '443:443'
    networks:
      env-network:

networks:
  env-network:
    driver: bridge